-- V7__create_users_table.sql

CREATE TABLE users (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    account_non_expired BOOLEAN,
    account_non_locked BOOLEAN,
    credentials_non_expired BOOLEAN,
    enabled BOOLEAN,
    full_name VARCHAR(255),
    password VARCHAR(255),
    user_name VARCHAR(255) UNIQUE
);
