CREATE TABLE app_user (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    birth_date DATE,
    cpf VARCHAR(11),
    created_at TIMESTAMP WITHOUT TIME ZONE,
    email VARCHAR(100),
    first_name VARCHAR(50),
    gender VARCHAR(255),
    last_name VARCHAR(100),
    updated_at TIMESTAMP WITHOUT TIME ZONE,

    CONSTRAINT app_user_pkey PRIMARY KEY (id),
    CONSTRAINT uk_email UNIQUE (email),
    CONSTRAINT uk_cpf UNIQUE (cpf),
    CONSTRAINT app_user_gender_check CHECK (gender IN ('Masculino', 'Feminino'))
)