-- V8__create_user_profile_table.sql

CREATE TABLE user_profile (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    birth_date DATE,
    cpf VARCHAR(11) UNIQUE,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE,
    first_name VARCHAR(50),
    gender VARCHAR(255) CHECK (gender IN ('MASCULINO', 'FEMININO')),
    last_name VARCHAR(100),
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE,
    user_id BIGINT UNIQUE,
    CONSTRAINT fk_user_profile_user FOREIGN KEY (user_id) REFERENCES users (id)
);
