
CREATE TABLE public.exercise_instruction (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    indicator VARCHAR(1),
    text TEXT,
    exercise_id BIGINT,
    CONSTRAINT fk_exercise FOREIGN KEY (exercise_id) REFERENCES public.exercise (id)
);