CREATE TABLE question_option (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    option_indicator VARCHAR(2),
    option_text TEXT,
    question_id BIGINT,
    CONSTRAINT fk_question_option_question FOREIGN KEY (question_id)
        REFERENCES question (id)
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);
