CREATE TABLE question_option (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    option_indicator CHARACTER VARYING(2),
    option_text TEXT,
    question_id BIGINT,

    CONSTRAINT option_key PRIMARY KEY (id),
    CONSTRAINT fkpixs1vg0b95g74f2c3nul8q7x FOREIGN KEY (question_id) REFERENCES question (id)
)