CREATE TABLE questions_statistics
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    correct_questions integer,
    exercises_completed integer,
    user_id bigint,
    CONSTRAINT questions_statistics_pkey PRIMARY KEY (id),
    CONSTRAINT ukqjj6c78g6psj99idwosxy8tli UNIQUE (user_id),
    CONSTRAINT fkpes9ya74xqu7bg3vsq9v10yhm FOREIGN KEY (user_id)
        REFERENCES app_user (id)
);