
CREATE TABLE public.question_option (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    option_indicator VARCHAR(2),
    option_text TEXT,
    question_id BIGINT,
    CONSTRAINT fk_question FOREIGN KEY (question_id) REFERENCES public.question (id)
);