CREATE TABLE questions_statistics (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    correct_questions INTEGER,
    exercises_completed INTEGER
);

-- Essa tabela vai receber um ID de User como FK