-- V13__create_user_question_table.sql

CREATE TABLE user_question (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    status VARCHAR(255) CHECK (status IN ('CORRETO', 'INCORRETO')),
    question_id BIGINT,
    user_id BIGINT,
    CONSTRAINT fk_user_question_question FOREIGN KEY (question_id)
        REFERENCES question (id) ON UPDATE NO ACTION ON DELETE NO ACTION,
    CONSTRAINT fk_user_question_user FOREIGN KEY (user_id)
        REFERENCES users (id) ON UPDATE NO ACTION ON DELETE NO ACTION
);
