
CREATE TABLE public.users (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    account_non_expired BOOLEAN,
    account_non_locked BOOLEAN,
    credentials_non_expired BOOLEAN,
    enabled BOOLEAN,
    full_name VARCHAR(255),
    password VARCHAR(255),
    user_name VARCHAR(255) UNIQUE,
    question_statistics_id BIGINT UNIQUE,
    user_profile_id BIGINT UNIQUE,
    CONSTRAINT fk_question_statistics FOREIGN KEY (question_statistics_id) REFERENCES public.questions_statistics (id),
    CONSTRAINT fk_user_profile FOREIGN KEY (user_profile_id) REFERENCES public.user_profile (id)
);