CREATE TABLE IF NOT EXISTS questions_statistics (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    correct_questions INTEGER,
    exercises_completed INTEGER,
    user_id BIGINT UNIQUE,
    CONSTRAINT fk_questions_statistics_user FOREIGN KEY (user_id)
        REFERENCES users (id)
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);
