security:
  jwt:
    token:
      secret-key: ${JWT_TOKEN_SECRETKEY}
      expire-length: 3600000
cors:
  originPatterns: http://localhost:8080
spring:
  application:
    name: application
  datasource:
    url: jdbc:postgresql://localhost:5432/devquest
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
  ai:
    openai:
      api-key: ${env.SPRING.AI.OPENAI.APIKEY}
logging:
  level:
    root: INFO