spring:
  application:
    name: application
  datasource:
    url: jdbc:postgresql://localhost:5432/devquest
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  ai:
    openai:
      api-key: ${env.SPRING.AI.OPENAI.APIKEY}