CREATE TABLE public.user_question (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    status VARCHAR(255) CHECK (status IN ('CORRETO', 'INCORRETO')),
    question_id BIGINT,
    user_id BIGINT,
    CONSTRAINT fk_question FOREIGN KEY (question_id) REFERENCES public.question (id),
    CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES public.users (id)
);